query EventStandingsQuery($slug: String!, $page: Int, $perPage: Int) {
	event(slug: $slug) {
    name
    tournament {
      name
      id
    }
    name
    id
    startAt
    numEntrants
    standings (query : {
      perPage: $perPage,
      page: $page
    }){
      pageInfo {
        total
        totalPages
      }
      nodes {
        placement
        entrant {
          isDisqualified
          id
          name
          initialSeedNum
          participants {
            user {
              id
              discriminator
            }
            player {
              id
              gamerTag
            }
          }
        }
      }
    }
  }
}