query EventStandingsQuery($slug: String!, $numEntrants: Int) {
	event(slug: $slug) {
    name
    tournament {
      name
      id
    }
    name
    id
    startAt
    numEntrants
    standings (query : {
      perPage: $numEntrants,
      page: 1
    }){
      nodes {
        placement
        entrant {
          id
          name
          initialSeedNum
          participants {
            user {
              id
              discriminator
            }
            player {
              gamerTag
            }
          }
        }
      }
    }
  }
}