query EventSetsQuery($slug: String!, $page: Int, $perPage: Int) {
    event(slug: $slug) {
        sets  (page: $page, perPage: $perPage)  {
            nodes {
                games {
				    winnerId
                }
                round
                slots{
                    entrant {
                        id
                        name
                        participants {
                            player {
                                id
                                gamerTag
                            }
                            user {
                                slug
                            }
                        }
                        initialSeedNum
                    }
                    standing {
                        stats {
                            score {
                                value   
                            }
                        }
                    }
                }
            }
        }
    }
}