query EventStandingsQuery($slug: String!, $page: Int!, $perPage: Int) {
	event(slug: $slug) {
    standings (query : {page: $page, perPage: $perPage}){
      pageInfo {
        totalPages
      }
      nodes {
        placement
        entrant {
          isDisqualified
          id
          name
          initialSeedNum
          participants {
            user {
              id
              discriminator
            }
            player {
              id
              gamerTag
            }
          }
        }
      }
    }
  }
}