query UserInfo($slug : String!){
    user(slug: $slug){
        id
        player {
            id
            gamerTag
          	prefix
        }
        genderPronoun
        location {
            country
            state
            city
        }
        email
    }
}